"""creating players

Revision ID: 04c7eddfced8
Revises: 704cb7251e3a
Create Date: 2021-11-09 17:17:27.662753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c7eddfced8'
down_revision = '704cb7251e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
